rem connect CM intelligent components with CK env
set ML_MODEL_IMAGE_HEIGHT=224
set ML_MODEL_IMAGE_WIDTH=224
set CK_BATCH_SIZE=1
set CK_BATCH_COUNT=1
set CK_ENV_ONNX_MODEL_ONNX_FILEPATH=
set CK_ENV_DATASET_IMAGENET_PREPROCESSED_DIR=%CM_DATASET_PREPROCESSED_PATH%
set CK_ENV_DATASET_IMAGENET_PREPROCESSED_SUBSET_FOF=%CM_DATASET_PREPROCESSED_PATH%\names.txt
set CK_CAFFE_IMAGENET_SYNSET_WORDS_TXT=%CM_DATASET_AUX_PATH%\synsets.txt
set CK_ENV_DATASET_IMAGENET_PREPROCESSED_DATA_TYPE=float32
set CK_RESULTS_DIR=%CM_TMP_CURRENT_SCRIPT_PATH%\results
set ML_MODEL_DATA_TYPE=float32
set USE_LLVM=no


set CK_BATCH_SIZE=%CM_BATCH_SIZE%
set CK_BATCH_COUNT=%CM_BATCH_COUNT%

%CM_PYTHON_BIN% -m pip install -r %CM_TMP_CURRENT_SCRIPT_PATH%\requirements.txt
IF %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%

%CM_PYTHON_BIN% %CM_TMP_CURRENT_SCRIPT_PATH%\src\pytorch_classify_preprocessed.py
IF %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%
