if exist %CM_DOCKERFILE_WITH_PATH% (
  echo .git > .dockerignore
  echo docker build %CM_DOCKER_CACHE_ARG%  %CM_DOCKER_BUILD_ARGS% -f %CM_DOCKERFILE_WITH_PATH% -t %CM_DOCKER_IMAGE_REPO%/%CM_DOCKER_IMAGE_NAME%:%CM_DOCKER_IMAGE_TAG% .
rem  echo.
rem  echo docker build %CM_DOCKER_CACHE_ARG%  %CM_DOCKER_BUILD_ARGS% -f %CM_DOCKERFILE_WITH_PATH% -t %CM_DOCKER_IMAGE_REPO%:%CM_DOCKER_IMAGE_TAG% .

rem  docker build %CM_DOCKER_CACHE_ARG%  %CM_DOCKER_BUILD_ARGS% -f "%CM_DOCKERFILE_WITH_PATH%" -t "%CM_DOCKER_IMAGE_REPO%/%CM_DOCKER_IMAGE_NAME%:%CM_DOCKER_IMAGE_TAG%" .
  echo.
  docker build %CM_DOCKER_CACHE_ARG%  %CM_DOCKER_BUILD_ARGS% -f "%CM_DOCKERFILE_WITH_PATH%" -t "%CM_DOCKER_IMAGE_REPO%/%CM_DOCKER_IMAGE_NAME%:%CM_DOCKER_IMAGE_TAG%" .
  IF %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%

  rem TO CHECK IMAGE RUN FROM HERE LATER ...

)
