del /Q %CM_JAVAC_PREBUILT_FILENAME%.zip

wget --no-check-certificate %CM_JAVAC_PREBUILT_URL%%CM_JAVAC_PREBUILT_FILENAME%.zip
IF %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%

unzip %CM_JAVAC_PREBUILT_FILENAME%.zip
IF %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%

del /Q %CM_JAVAC_PREBUILT_FILENAME%.zip
