@echo off

echo %CD%

if not "%CM_EXTRACT_CMD0%" == "" (
 echo %CM_EXTRACT_CMD0%
 %CM_EXTRACT_CMD0%
 IF %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%
)

echo %CM_EXTRACT_CMD%
%CM_EXTRACT_CMD%
IF %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%
  
echo %CM_EXTRACT_EXTRACTED_CHECKSUM_CMD%
%CM_EXTRACT_EXTRACTED_CHECKSUM_CMD%
IF %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%
